TransShip/Controllers/AdminController.cs
using System.Web.Mvc;
using TransShip.Models;
using TransShipModel.Abstract;
using TransShip.LogBook;
using System.Web.Security;
using TransShipModel.DTO;
using System.Collections.Generic;

namespace TransShip.Controllers
{
    public class AdminController : Controller
    {
        private readonly INSecurity _securityRepository;



        public AdminController(INSecurity securityRepository)
        {
            _securityRepository = securityRepository;
        }

        private string GetUserType() {
            if (User.Identity.Name != null) {
                List<UserInformation> users = _securityRepository.GetUserInformation(User.Identity.Name);
                if (users.Count > 0) {
                    var user = users[0];
                    return user.user_type;
                }
            }
            return "";
        }

        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(User.Identity.Name)) {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Admin()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            
            ViewData["Message"] = "Admin page.";

            return View();
        }

        public ActionResult Users()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = _securityRepository.GetUserList();
            return View(model: dataModel);
        }

        public ActionResult EditUser() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = _securityRepository.GetUserList();
            return View(model: dataModel);
        }

        public ActionResult changePass() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";

            return View();
        }

        public ActionResult Countries()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = _securityRepository.GetCountryList();
            return View(model: dataModel);
        }

        public ActionResult Countrie() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = "hola";
            return View(model: dataModel);
        }

        public ActionResult File_Type() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = "hola";
            return View(model: dataModel);
        }

        public ActionResult Service_Type() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = "hola";
            return View(model: dataModel);
        }

        public ActionResult Customers() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = "hola";
            return View(model: dataModel);
        }

        public ActionResult MemberShip() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = "hola";
            return View(model: dataModel);
        }

        public ActionResult AproveRegister()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Admin page.";
            var dataModel = _securityRepository.GetPendingCustomers();
            return View(model: dataModel);
        }
        
        public ActionResult Vendors()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Vendors";
            
            return View();
        }

        public ActionResult Files(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;
            ViewData["Message"] = "Files";

            return View();
        }

        public ActionResult Notes(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;
            ViewData["Message"] = "View Shipment";

            return View();
        }

        public ActionResult ViewShipment(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;
            ViewData["Message"] = "View Shipment";
            
            return View();
        }

        public ActionResult CancelShipment(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;
            ViewData["Message"] = "Cancel Shipment";
            
            return View();
        }

        public ActionResult DeliveryShipment(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;
            ViewData["Message"] = "Delivery Shipment";

            return View();
        }

        public ActionResult ShipmentTracking(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;
            ViewData["Message"] = "Shipment Tracking";
            
            return View();
        }

        public ActionResult Shipments()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "T") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Shipments";
            
            return View();
        }
    }
}

TransShip/Controllers/CustomerController.cs
using System.Web.Mvc;
using TransShip.Models;
using TransShipModel.Abstract;
using TransShip.LogBook;
using System.Web.Security;
using TransShipModel.DTO;
using System.Collections.Generic;

namespace TransShip.Controllers
{
    public class CustomerController : Controller
    {
        private readonly INSecurity _securityRepository;

        public CustomerController(INSecurity securityRepository)
        {
            _securityRepository = securityRepository;
        }

        private string GetUserType() {
            if (User.Identity.Name != null) {
                List<UserInformation> users = _securityRepository.GetUserInformation(User.Identity.Name);
                if (users.Count > 0) {
                    var user = users[0];
                    return user.user_type;
                }
            }
            return "";
        }

        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Customer()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index","Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult EditProfile() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult EditUsers() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult Contact() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult Address() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult changePass() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult billing() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult Shipments() {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Customer page.";

            return View();
        }

        public ActionResult Notes(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;

            return View();
        }

        public ActionResult Files(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;

            return View();
        }

        public ActionResult approveQuotes(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;

            return View();
        }

        public ActionResult shipmentTracking(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;

            return View();
        }

        public ActionResult viewShipment(int shipmentId) {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["shipmentId"] = shipmentId;

            return View();
        }

        public ActionResult Profile()
        {
            if (string.IsNullOrEmpty(User.Identity.Name) || GetUserType() != "C") {
                return RedirectToAction("Index", "Home");
            }
            ViewData["Message"] = "Edit Profile";
            var dataModel = _securityRepository.GetUserList();
            return View(model: dataModel);
        }

        
    }
}

TransShip/Controllers/Service_TypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;
using TransShipBO.BO;
using TransShipModel;
using TransShipModel.Responses;

namespace TransShip.Controllers
{
    public class Service_TypeController : ApiController
    {
        [EnableCors(origins: "*", headers: "*", methods: "GET, POST, PUT, DELETE, OPTIONS")]
        public HttpResponseMessage Get() {
            try {

                BOService_types service = new BOService_types();

                var listServices = new List<service_types>();
                listServices = service.GetServices();
                return Request.CreateResponse(HttpStatusCode.OK, listServices);

            } catch (Exception e) {
                ErrorMessage message = new ErrorMessage("2.1", "Exception to get services types - " + e.GetBaseException().Message, e.ToString());
                return Request.CreateResponse(HttpStatusCode.InternalServerError, message);
            }

        }

        public HttpResponseMessage Post(service_types model) {
            try {
                BOService_types service = new BOService_types();
                service_types fileService;

                fileService = service.SaveService(model);
                return Request.CreateResponse(HttpStatusCode.OK, fileService);
            } catch (Exception e) {
                ErrorMessage message = new ErrorMessage("2.1", "Exception to save service type - " + e.GetBaseException().Message, e.ToString());
                return Request.CreateResponse(HttpStatusCode.InternalServerError, message);
            }

        }

        public HttpResponseMessage Put(service_types model) {
            try {
                BOService_types service = new BOService_types();
                service_types serviceType;

                serviceType = service.UpdateService(model);
                return Request.CreateResponse(HttpStatusCode.OK, serviceType);
            } catch (Exception e) {
                ErrorMessage message = new ErrorMessage("2.1", "Exception to update service type - " + e.GetBaseException().Message, e.ToString());
                return Request.CreateResponse(HttpStatusCode.InternalServerError, message);
            }

        }

        public HttpResponseMessage Delete(int id) {
            try {
                BOService_types service = new BOService_types();

                var delete = service.DeleteService(id);

                return Request.CreateResponse(HttpStatusCode.OK, delete);
            } catch (Exception e) {
                ErrorMessage message = new ErrorMessage("2.1", "Exception to update service type - " + e.GetBaseException().Message, e.ToString());
                return Request.CreateResponse(HttpStatusCode.InternalServerError, message);
            }

        }
    }
}

TransShip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Obaju e-commerce template">
    <meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
    <meta name="keywords" content="">
    <title>@ViewData["Title"] - TransShip</title>
    <meta name="keywords" content="">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/cf663153b8.css">

    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/owl.carousel.css" rel="stylesheet" />
    <link href="~/Content/owl.theme.css" rel="stylesheet" />
    <link href="~/Content/style.default.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery.cookie.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="~/Scripts/waypoints.min.js"></script>
    <script src="~/Scripts/modernizr.js"></script>
    <script src="~/Scripts/bootstrap-hover-dropdown.js"></script>
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/Scripts/knockout.mapping.js"></script>
    <script src="~/Content/datatables/datatables.min.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/underscore-min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/numeral.min.js"></script>
    <script src="~/Scripts/blockUI.js"></script>

    <script src="~/Content/custom/model.js"></script>
    <script src="~/Content/custom/scripts.js"></script>
    <script src="~/Content/custom/register.js"></script>


</head>

<body>
    <script>
        $(document).ready(function () {
            console.log("applyBindings");
            ko.applyBindings();

            model.register.initialize();
        });
    </script>

    @{
        if (string.IsNullOrEmpty((string)ViewData["result"]) == false) {
            <div class="alert alert-success">
                <strong>Account confirmed!</strong> Transship will contact you to approve your account.
            </div>
        }
        if ((string)ViewData["Message"] == "Invalid credentials") {
            <div class="alert alert-warning">
                <strong>Invalid credentials!</strong>
            </div>
        }
    }
    <div class="modal fade" id="forgot-password" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Forgot Password</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-10">
                            <input type="text" data-bind="value: model.recover.email" class="form-control" id="recoveremail" name="recoveremail" placeholder="Registered email">
                        </div>
                    </div>
                    <div class="form-group"></div>
                    <div class="form-group">
                        <p class="text-center">
                            <button type="button" class="btn btn-info mybtn" data-bind="click: recoverPassword" data-dismiss="modal"><i class="fa fa-sign-in"></i> Recover</button>
                            <button type="button" class="btn btn-default mybtn" data-dismiss="modal"><i class="fa fa-power-off"></i> Cancel</button>
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="alert alert-success" data-bind="visible: model.recoversuccess() == 'success'">
                        <strong>Success!</strong> We sent you an email for password recovery. Check your inbox
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Login</h4>
                </div>
                <div class="modal-body">
                    <form action=@Url.Action("Index", "Home") method="POST">
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <input type="text" class="form-control" id="email" name="email" placeholder="email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="password" name="password" placeholder="password">
                        </div>

                        <p class="text-center">
                            <button class="btn btn-primary mybtn" type="submit"><i class="fa fa-sign-in"></i> Log in</button>
                        </p>
                    </form>
                    <ul class="menu">
                        <li>
                            <a href="#" data-toggle="modal" data-target="#forgot-password" data-dismiss="modal">Forgot password?</a>
                        </li>
                        <li>
                            <a href="#" data-toggle="modal" data-target="#register-modal" data-dismiss="modal">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="top">
        <div class="container">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
                <ul class="menu">
                    @if (Request.IsAuthenticated) {
                        if (ViewData["customerId"] != null) {
                            <li>
                                @Html.ActionLink("My Account", "Shipments", "Customer")
                            </li>
                        } else {
                            <li>
                                @Html.ActionLink("Administration", "Shipments", "Admin")
                            </li>
                        }

                        <li>
                            <span style="color: white;"><i class="glyphicon glyphicon-user"></i> @User.Identity.Name</span>
                        </li>
                        <li>
                            @Html.ActionLink("Log Out", "LogOff", "Home")
                        </li>
                    } else {
                        <li>
                            <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                        </li>
                        <li>
                            @Html.ActionLink("Register", "Register", "Home")
                        </li>
                    }
                </ul>
            </div>
        </div>







    </div>

    <!-- *** TOP BAR END *** -->
    <!-- *** NAVBAR ***
    _________________________________________________________ -->

    <div class="navbar navbar-default yamm" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-header">

                <a class="navbar-brand home" href="/" data-animate-hover="bounce">
                    <img src="~/images/TransShipLogo.png" alt="Transship" class="hidden-xs" style="max-width: 250px; margin-top: +10px;">
                    <img src="~/images/TransShipLogo.png" alt="Transship" class="visible-xs" style="max-width: 250px; margin-top: +10px;"><span class="sr-only">Transship - go to homepage</span>
                </a>
                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-align-justify"></i>
                    </button>

                </div>
            </div>
            <!--/.navbar-header -->

            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-left"></ul>

            </div>
            <!--/.nav-collapse -->

            <div class="navbar-buttons">


                <!--/.nav-collapse -->



            </div>

            <!--/.nav-collapse -->

        </div>
        <!-- /.container -->
    </div>
    <!-- /#navbar -->
    <!-- *** NAVBAR END *** -->

    <div id="all">

        <div id="content">
            <div class="container body-content">
                @RenderBody()
            </div>
        </div><!-- /#content -->
        <!-- *** FOOTER ***
        _________________________________________________________ -->
        <div id="footer">
            <div class="container">
                <div class="row">


                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#footer -->
        <!-- *** FOOTER END *** -->
        <!-- *** COPYRIGHT ***
        _________________________________________________________ -->
        <div id="copyright">
            <div class="container">
                <div class="col-md-6">
                    <p class="pull-left">© 2017 Transship</p>

                </div>
                <div class="col-md-6">
                    <p class="pull-right">
                        <!--
                        Template by <a href="http://bootstrapious.com/e-commerce-templates">Bootstrapious</a> with support from <a href="https://kakusei.cz">Kakusei</a>
                         Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
                    </p>
                </div>
            </div>
        </div>
        <!-- *** COPYRIGHT END *** -->
    </div>




</body>
</html>

TransShip/Views/Shared/_LayoutRecoverPassword.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Obaju e-commerce template">
    <meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
    <meta name="keywords" content="">
    <title>@ViewData["Title"] - TransShip</title>
    <meta name="keywords" content="">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/cf663153b8.css">

    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/owl.carousel.css" rel="stylesheet" />
    <link href="~/Content/owl.theme.css" rel="stylesheet" />
    <link href="~/Content/style.default.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery.cookie.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/waypoints.min.js"></script>
    <script src="~/Scripts/modernizr.js"></script>
    <script src="~/Scripts/bootstrap-hover-dropdown.js"></script>
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/Scripts/knockout.mapping.js"></script>
    <script src="~/Content/datatables/datatables.min.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/underscore-min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/numeral.min.js"></script>
    <script src="~/Scripts/blockUI.js"></script>

    <script src="~/Content/custom/model.js"></script>
    <script src="~/Content/custom/scripts.js"></script>
    <script src="~/Content/custom/register.js"></script>

</head>



<body>
    <script>
        $(document).ready(function () {
            console.log("applyBindings");
            ko.applyBindings();

            model.register.initialize();

        });
    </script>
    <div id="all">

        <div id="content">
            <div class="container body-content">
                @RenderBody()
            </div>
        </div><!-- /#content -->
        <!-- *** FOOTER ***
        _________________________________________________________ -->
        <div id="footer">
            <div class="container">
                <div class="row">


                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#footer -->
        <!-- *** COPYRIGHT ***
        _________________________________________________________ -->
        <div id="copyright">
            <div class="container">
                <div class="col-md-6">
                    <p class="pull-left">© 2017 Transship</p>

                </div>
                <div class="col-md-6">
                    <p class="pull-right">
                        <!--
                        Template by <a href="http://bootstrapious.com/e-commerce-templates">Bootstrapious</a> with support from <a href="https://kakusei.cz">Kakusei</a>
                         Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
                    </p>
                </div>
            </div>
        </div>
        <!-- *** COPYRIGHT END *** -->
    </div>




</body>
</html>